[package]
name = "aoc"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indicatif = {version = "0.17.7", features = ["rayon"]}
num = "0.4.1"
regex = "1.10.2"
rstest = "0.18.2"
